/* See LICENSE file for copyright and license details. */

static const char *html_header1 =
	"<!DOCTYPE html>\n"
	"<html>\n"
	"<head>\n"
	"<meta charset=\"utf-8\"/>\n"
	"<title>";
static const char *html_header2 =
	"</title>\n"
	"</head>\n"
	"<body>\n";
static const char *html_footer =
	"<hr/>\n"
	"<small>Generated by mailarchiver " VERSION "</small>\n"
	"</body>\n"
	"</html>\n";

