/* See LICENSE file for copyright and license details. */

#define MAX_FILENAME_LENGTH 256

/* The 'aether' is a big scratch space used for temporary allocations.
 * It is allocated via demand paging, meaning memory is only actually
 * allocated when it is actually needed.
 * MAX_AETHER_MEMORY specifies the maximum number of bytes in the aether. */
#define MAX_AETHER_MEMORY (256 * 1024 * 1024)

static const char *html_header1 =
	"<!DOCTYPE html>\n"
	"<html>\n"
	"<head>\n"
	"<meta charset=\"utf-8\"/>\n"
	"<title>";
static const char *html_header2 =
	"</title>\n"
	"</head>\n"
	"<body>\n";
static const char *html_footer =
	"<hr/>\n"
	"<small>Generated by smak " VERSION "</small>\n"
	"</body>\n"
	"</html>\n";

