.Dd August 10, 2022
.Dt MAILARCHIVER 1
.Os
.Sh NAME
.Nm mailarchiver
.Nd mailing list web archiver
.Sh SYNOPSIS
.Nm
.Ar mail-file
.Sh DESCRIPTION
At some point,
.Nm
might become a fully fledged mailing list web archiver.
For the time being, it is merely a proof-of-concept.
.sp
Executing
.Nm
with a file containing a mail message as the argument
will print a formatted HTML version of the message to stdout.
.Sh AUTHORS
.An Thomas Oltmann Aq Mt thomas.oltmann.hhg@gmail.com
